<Project Sdk="Microsoft.NET.Sdk">
  <!-- To reduce build times, we only enable analyzers for the newest TFM -->
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net47;net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <!--
      Versions 3.0.0 and above does not support net47(0) anymore.
      As long as we want to build for net47 we need to reference version below V3.
    -->
    <PackageReference Include="xunit.runner.visualstudio" Version="[2.8.2]">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\AwesomeAssertions.Json\AwesomeAssertions.Json.csproj" />
  </ItemGroup>

</Project>
